export const Meals = [
  {
    id: 1,
    category: "Pakistan",
    foods: [
      {
        foodId: 1,
        name: "Chicken Seekh Kabab",
        duration: "30",
        complexity: "Simple",
        affordability: "affordable",
        imageName: require("../assets/images/Chicken-Seekh-kabab-PK.jpg"),
        desc: "Seekh is a metal skewer. Seekh Kabab or seekh kebab is a South Asian entree in which marinated beef mince is covered on the seekh to make a long cylindrical hollow kabab and the kababs are then barbecued on coal. Seekh kabab found its way to Pakistani cuisine through the influence of Mughlai Cuisine.",
        ingredients: [
          "Ground chicken with fat: Chicken grounded with white chicken fat is essential for making juicy seekh kababs. I used boneless chicken and grounded it with white fat around the chicken in a food processor.",
          "Onions: We need finely chopped onions for this recipe. I did my chopping in the food processor and squeezed the chopped onion lightly between my palms to remove excess water.",
          "Ginger and Garlic: I chopped ginger and garlic too in the food processor separately. If chopped ginger is watery, squeeze it lightly too and discard the water.",
          "Herbs: I used fresh cilantro/coriander only. You can use mint and parsley too.",
          "Green chilies: Use medium-sized moderately spicy chilies for extra. You may skip it for less spicy kabab.",
          "Seekh kabab spice mix: I have shared the recipe for the Spice mix in the recipe card, which I like best. You can also use ready-made spice mix.",
          "Fat: To ensure seekh kabab are soft and juicy, I used butter and cream too in this recipe. Chicken mince is low-fat so adding fat makes soft kababs.",
        ],
      },
      {
        foodId: 2,
        name: "Pakistani Chicken Tikka",
        duration: "40",
        complexity: "Simple",
        affordability: "affordable",
        imageName: require("../assets/images/Chicken-tikka-PK.jpg"),
        desc: "The tandoori chicken is often referred to as Chicken Tikka Thigh or Breast in Pakistan.So if the bone in the version of tandoori chicken is called chicken tikka in Pakistan then what is the boneless chicken tikka version called? It is called Chicken tikka boti or Chicken tikka kabab.",
        ingredients: [
          "Chicken: Use medium-sized chicken pieces that weigh 750 grams. (Live chicken weighs 1-1.25 kg) Smaller chicken has tender meat. The bigger bird would require longer marination of at least 8 hours.",
          "Wet spices: The wet spices are ginger, garlic, green chili, and papaya paste on the round plate. Papaya paste is used as a meat tenderizer.",
          "Common Pakistani spices: Tikka doesn't require tons of spices like achari chicken. The dry spices are common Pakistani spices like cumin, coriander, turmeric, garam masala, salt, red chili flakes, and Kashmiri chili powder",
          "Kashmiri chili has a bright red color and a moderately spicy taste. You can substitute Kashmiri chili powder with paprika, and extra chili powder.",
          "Yogurt: Yogurt adds a little tanginess and is also a meat tenderizer.",
          "Lemon: Lemon helps with the tanginess.",
        ],
      },
      {
        foodId: 3,
        name: "Chicken Chargha",
        duration: "60",
        complexity: "hard",
        affordability: "affordable",
        imageName: require("../assets/images/chicken-chargha-PK.jpg"),
        desc: "Get this Pakistani-style, spicy fried chicken recipe that requires very little active time. You first steam the Lahori chargha for the juiciest tender chicken followed by deep-frying for a crispy crust.",
        ingredients: [
          "Chicken: 1 kg to 1.25 kg skinless whole chicken works best for Chicken Chargha. Because the flesh of a smaller bird is tender and cooks quickly. If getting a live hen from the slaughterhouse, a chicken weighing around 1.5 kg to 1.75 kg.",
          "Cornflour: Cornflour helps us give some crispy crust to this chicken. You can use other flours too like rice flour or similar flours.",
          "Kashmiri Chili: This ingredient is particular for color. You can use a combo of cayene pepper and paprika to skip it.",
          "Egg: Egg helps the spice marinade to stick to the skin.",
          "Garam Masala: Garam masala is a mixture of varioua spices. This can be skipped if you don't have it.",
          "Chaat masala: Chaat masala is essential for chargha and it is easily available in Pakistani stores. This condiment can be sprinkled like pepper on most foods and tastes yum. Go get it!",
          "Yellow color: This is again an optional ingredient. You can skip it or use very little red or orange color instead.",
          "Red chili flakes: You can sub red chili flakes with red chili powder.",
          "Vinegar: I used distilled vinegar, you can use lemon juice instead.",
          "Ginger and garlic paste: I forgot to add it in the ingredient shot.",
          "Common Pakistani spices: Turmeric, cumin, and coriander are other common spices used in this recipe.",
        ],
      },
    ],
  },
  {
    id: 2,
    category: "Indian",
    foods: [
      {
        foodId: 4,
        name: "Indian Chicken Curry",
        duration: "40",
        complexity: "Simple",
        affordability: "affordable",
        imageName: require("../assets/images/chicken-curry-IND.jpg"),
        desc: "This Indian-inspired creamy chicken curry recipe is similar to a curry I had in India. The aromatic spices and flavors are a delight to the senses! Delicious with fresh naan and basmati rice.",
        ingredients: [
          "3 tablespoons olive oil",
          "1 small onion, chopped",
          "2 cloves garlic, minced",
          "3 tablespoons curry powder",
          "1 teaspoon ground cinnamon",
          "1 teaspoon paprika",
          "1 bay leaf",
          "½ teaspoon grated fresh ginger root",
          "½ teaspoon white sugar",
          "salt to taste",
          "2 skinless, boneless chicken breast halves - cut into bite-size pieces",
          "1 tablespoon tomato paste",
          "1 cup plain yogurt",
          "¾ cup coconut milk",
          "½ lemon, juiced",
          "½ teaspoon cayenne pepper",
        ],
      },
      {
        foodId: 5,
        name: "Red Lentil Curry",
        duration: "55",
        complexity: "normal",
        affordability: "affordable",
        imageName: require("../assets/images/red-lentil-curry-IND.jpg"),
        desc: "This red lentil curry is rich and hearty. It's great as a main meal rather than a side dish like the more traditional Indian dhal. Don't let the ingredient list faze you — this is an easy dish to make. This dish is excellent served with basmati rice.",
        ingredients: [
          "2 cups red lentils",
          "3 cups water, or more as needed",
          "1 tablespoon vegetable oil",
          "1 large onion, diced",
          "2 tablespoons curry paste",
          "1 tablespoon curry powder",
          "1 teaspoon ground turmeric",
          "1 teaspoon ground cumin",
          "1 teaspoon chili powder",
          "1 teaspoon salt",
          "1 teaspoon white sugar",
          "1 teaspoon minced garlic",
          "1 teaspoon minced fresh ginger",
          "1 (14.25 ounce) can tomato puree",
        ],
      },
      {
        foodId: 6,
        name: "Indian Butter Chicken",
        duration: "40",
        complexity: "Simple",
        affordability: "affordable",
        imageName: require("../assets/images/Butter-Chicken-IND.jpg"),
        desc: "This butter chicken recipe, or chicken makhani, is one of my favorite Indian dishes. It features a full-flavored sauce that complements the chicken well. It can be made as mild or spicy as you wish by adjusting the cayenne. Serve with basmati rice and naan bread.",
        ingredients: [
          "2 tablespoons peanut oil, divided",
          "1 shallot, finely chopped",
          "¼ white onion, chopped",
          "2 tablespoons butter",
          "1 tablespoon ginger garlic paste",
          "2 teaspoons lemon juice",
          "2 teaspoons garam masala, divided",
          "1 teaspoon chili powder",
          "1 teaspoon ground cumin",
          "1 bay leaf",
          "1 cup tomato puree",
          "1 cup half-and-half",
          "¼ cup plain yogurt",
          "1 pinch salt and ground black pepper to taste",
          "1 pound boneless, skinless chicken thighs, cut into bite-size pieces",
          "¼ teaspoon cayenne pepper, or to taste",
          "1 tablespoon cornstarch",
          "¼ cup water",
        ],
      },
      {
        foodId: 7,
        name: "Tandoori Chicken",
        duration: "40",
        complexity: "normal",
        affordability: "affordable",
        imageName: require("../assets/images/Tandoori-Chicken-IND.jpg"),
        desc: "Try this authentic tandoori chicken that's marinated in yogurt and spices, then cooked on the grill instead of a clay oven so you can make it at home. Serve with long-grain basmati rice, grilled veggies, roasted corn on the cob, and a cucumber salad.",
        ingredients: [
          "2 pounds chicken, cut into pieces",
          "1 medium lemon, juiced",
          "1 teaspoon salt",
          "1 ¼ cups plain yogurt",
          "½ medium onion, finely chopped",
          "1 clove garlic, minced",
          "2 teaspoons garam masala",
          "1 teaspoon grated fresh ginger root",
          "1 teaspoon cayenne pepper",
          "1 teaspoon red food coloring (Optional)",
          "1 teaspoon yellow food coloring (Optional)",
          "2 teaspoons finely chopped cilantro",
          "1 medium lemon, cut into wedges",
        ],
      },
    ],
  },
  {
    id: 3,
    category: "Italian",
    foods: [
      {
        foodId: 8,
        name: "Carrot Pasta Sauce ",
        duration: "30",
        complexity: "Simple",
        affordability: "affordable",
        desc: " This is a quick and easy pasta recipe that you can eat anytime as breakfast or snack. The special thing about this pasta recipe is that carrots have been used along with tomatoes to make the sauce.",
        imageName: require("../assets/images/Carrot-Pasta-Sauce-ITL.jpg"),
        ingredients: [
          "350 gms boiled pasta of your own choice",
          "250 gram carrots, chopped into small pieces",
          "2 small tomatoes",
          "1 medium-sized onion cut into quarters",
          "4 garlic cloves, chopped",
          "Olive oil or oil of your choice",
          "1 cup Vegetable broth",
          "Spices (Salt, black, white, and cayenne pepper)",
          "One cup of fresh cream (optional)",
          "Dried herbs and oregano (optional)",
        ],
      },
      {
        foodId: 9,
        name: "Cheesy Pasta with Vegetables",
        duration: "40",
        complexity: "Simple",
        affordability: "affordable",
        imageName: require("../assets/images/cheesy-vegetable-pasta-ITL.jpg"),
        desc: "This is a delicious pasta made with vegetables, cheesy and milk. This Cheesy Pasta can be a comforting meal for those when you don't want to spend so much time in the kitchen.",
        ingredients: [
          "2 Cups your favourite pasta",
          "2 tbsp olive oil",
          "2 cups vegetables (broccoli, corn, bell peppers, mushrooms, etc.)",
          "2 tbsp butter",
          "2 tbsp all-purpose flour",
          "2 cup milk",
          "2 cups shredded cheese (cheddar, mozzarella, parmesan, or a mix)",
          "Salt and pepper to taste",
        ],
      },
      {
        foodId: 10,
        name: "Oats Pizza Crust",
        duration: "30",
        complexity: "normal",
        affordability: "affordable",
        imageName: require("../assets/images/Oat-Flour-Crust-ITL.jpg"),
        desc: "If you are looking for healthy pizza alternative, then try this amazing pizza recipe, which can be made with nutritious oats flour.",
        ingredients: [
          "1 Cup oats",
          "1/2 cup whole wheat flour",
          "1 tsp baking powder",
          "A pinch of salt",
          "1/2 cup hung curd",
          "1 cup mixed vegetables (onion, bell peppers, cherry tomatoes, olives, spinach, etc.)",
          "1/4 cup crumbled feta or goat cheese or cottage cheese, grated",
          "Fresh basil leaves for garnish",
          "Pizza sauce to spread",
        ],
      },
      {
        foodId: 11,
        name: "Chilli Oil Butter Garlic Pasta",
        duration: "45",
        complexity: "Simple",
        affordability: "affordable",
        imageName: require("../assets/images/chilli-oil-garlic-pasta-ITL.jpg"),
        desc: " Chilli oil butter garlic pasta recipe includes spaghetti which is generously tossed in spicy homemade chili oil and butter garlic sauce. This dish is a fusion of Italian and Asian cuisine, which will leave you drooling over the strong and exotic flavours. You can prepare this easily at home in 30 minutes.",
        ingredients: [
          "2 cups oil",
          "4-5 crushed garlic cloves",
          "2 Green Onions, sliced",
          "1 tsp sliced ginger",
          "2-star anise",
          "1 bay leave",
          "1 cinnamon stick",
          "1 tbsp sichuan peppercorns or black pepper powder",
          "1/2 cup chili flakes",
          "2 tbsp red chili powder",
          "2 tbsp sesame seeds",
          "1 tsp salt (as per taste)",
          "2 cups al-dante spaghetti",
          "4 tbsp butter",
          "4-5 minced garlic",
          "1 tsp chili flakes",
          "1-2 tbsp light soy sauce (as per taste)",
          "2 green onions , chopped",
          "Parmesan Cheese",
        ],
      },
    ],
  },
];
